<?php

/**
 * The request is represented by global variables ($_GET, $_POST, ...)
 * The response is generated by functions (echo, header, setcookie, ...)
 * 
 * Symfony http-foundation replaces ...
 * those variables and functions with an OOP layer.
 * 
 * composer require symfony/http-foundation
 * 
 * The createFromGlobals() creates a Request object from PHP global variables,
 * The send() method sends the Response object back to the client,
 * 
 * php -S localhost:8000
 * http://localhost:8000/
 *      Hello World
 * http://localhost:8000/?name=Fabien
 *      Hello Fabien
 */

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

$request = Request::createFromGlobals();
$name = $request->get('name', 'World');

$response = new Response(sprintf('Hello %s', 
    htmlspecialchars($name, ENT_QUOTES, 'UTF-8')
));

$response->send();