controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: 'App\Controller\DefaultController::index'

hello:
    path: /hello/{name}
    controller: 'App\Controller\DefaultController::hello'