controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: 'App\Controller\DefaultController::index'

hello:
    path: /hello/{name}
    controller: 'App\Controller\DefaultController::hello'
    defaults:
        name: 'World'

page:
    path: /page/{id}
    controller: 'App\Controller\DefaultController::page'
    requirements: 
        id: \d+

page_slug:
    path: /{catg}/{slug}-{id}
    controller: 'App\Controller\DefaultController::seo'
    requirements:
        catg: '[a-z0-9-]+'
        slug: '[a-z0-9-]+'
        id: \d+

url:
    path: /url
    controller: 'App\Controller\DefaultController::url'