controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: 'App\Controller\DefaultController::index'

page:
    path: /page/{id}
    controller: 'App\Controller\DefaultController::page'
    defaults:
        id: 1
    requirements: 
        id: \d+

seo:
    path: /{catg}/{slug}-{id}
    controller: 'App\Controller\DefaultController::seo'
    requirements:
        catg: '[a-z0-9-]+'
        slug: '[a-z0-9-]+'
        id: \d+