<?php
/*
    http_foundation/index.php

    The request is represented by global variables ($_GET, $_POST)
    The response is generated by functions (echo, header, setcookie)
    This HttpFoundation replaces variables and functions with an OOP layer

    cd github/php-pages/main/framework/http_foundation/
    composer require symfony/http-foundation
    php -S localhost:8000

    http://localhost:8000/01.php
        Hello World
    http://localhost:8000/01.php?name=Fabien
        Hello Fabien
*/

require_once __DIR__.'/vendor/autoload.php';
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

$request = Request::createFromGlobals(); // from PHP global variables
$name = $request->get('name', 'World');

$response = new Response(sprintf('Hello %s', 
    htmlspecialchars($name, ENT_QUOTES, 'UTF-8')
));

$response->send(); // Response object back to the client